"""Initial migration.

Revision ID: 5f3ae18f4e20
Revises: 
Create Date: 2022-05-30 17:07:30.244951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3ae18f4e20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('divisao', sa.String(length=128), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('employee_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_records',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('NAME', sa.TEXT(), nullable=False),
    sa.Column('DIVISION', sa.TEXT(), nullable=False),
    sa.Column('STARS', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
