"""delete

Revision ID: 64fb59665d35
Revises: 99d4982dbc3b
Create Date: 2022-05-30 17:19:33.063571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64fb59665d35'
down_revision = '99d4982dbc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stars2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stars2')
    # ### end Alembic commands ###
